version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8080:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/devops_db
      - APP_ENV=production
      - DEBUG=False
volumes:
  postgres_data:
